#!/usr/bin/env python3
import sys
import requests

API_KEY = "be508a0a-53f3-455c-ad1a-8afc22852841"
API_URL = "https://radar.scorton.tech/analyze/url"

def scan_domain(domain):
    headers = {
        "x-api-key": API_KEY
    }

    payload = {
        "url": domain
    }

    response = requests.post(API_URL, headers=headers, data=payload)
    print("Status code:", response.status_code)
    return response.text

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} [nom_de_domaine]")
        sys.exit(1)

    domain = sys.argv[1]
    print(f"[+] Scan de : {domain}\n")

    result = scan_domain(domain)
    print(result)

if __name__ == "__main__":
    main()
